
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t vkothakapa/next-js-app
    - run: echo "${{secrets.DOCKERHUB_PASSWORD1}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME1}} --password-stdin 
    - run: docker push vijayvardhanreddy/next-js-app-githubactions:latest
